# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17e61f6233b3373ba997813d79a8be0e4ed33a4ee245583987977cd26cf92b4cee331132a9b88468803f4814fa7b8f7073962334d4352e3d5705c45a9282fd79

test:
  secret_key_base: ccda7722715aa17c3f9706582cf173ce590dba4f290577b4068fd2e71013263d625883e1269b00fbda7cb8ac75ab5e630a5ffaf756726533595038e864aff6a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
